name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image for testing
      - name: Build test Docker image
        run: docker build -t beoboe/react-test -f ./client/Dockerfile.dev ./client

      # Run tests
      - name: Run tests in Docker container
        run: docker run -e CI=true beoboe/react-test npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build production Docker images
      - name: Build production Docker images
        run: |
          docker build -t beoboe/multi-client ./client
          docker build -t beoboe/multi-server ./server
          docker build -t beoboe/multi-nginx ./nginx
          docker build -t beoboe/multi-worker ./worker

      # Login to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      # Push images to Docker Hub
      - name: Push Docker images
        run: |
          docker push beoboe/multi-client
          docker push beoboe/multi-server
          docker push beoboe/multi-nginx
          docker push beoboe/multi-worker

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: eu-north-1
        run: |
          zip -r app.zip .  # Zip the current directory
          aws s3 cp app.zip s3://elasticbeanstalk-eu-north-1-021660495013/docker-multi/app.zip
          aws elasticbeanstalk create-application-version --application-name multi-docker \
            --version-label $(date +%s) --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-021660495013,S3Key=docker-multi/app.zip
          aws elasticbeanstalk update-environment --environment-name Mutli-docker-env \
            --version-label $(date +%s)
